# Generated by Django 5.1.4 on 2024-12-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pdUrl',
            field=models.URLField(default='https://vk.com/pechebka'),
        ),
    ]
