# Generated by Django 5.1.4 on 2024-12-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dayMeter', models.IntegerField()),
                ('nightMeter', models.IntegerField()),
                ('accountNumber', models.PositiveIntegerField()),
            ],
        ),
    ]
