# Generated by Django 5.1.4 on 2024-12-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_bill_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_tarif', models.IntegerField(default=10)),
                ('night_tarif', models.IntegerField(default=15)),
            ],
        ),
    ]
